name: flutter_phajay
description: A Flutter library for showing PhaJay payment link screen.
version: 0.0.6
homepage: https://www.phajay.co/lo
repository: https://www.phajay.co/lo
issue_tracker: https://www.phajay.co/lo

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/en.png
    - assets/logo-phajay.png
