name: flutter_phajay
description: A Flutter library for showing PhaJay payment link screen.
version: 0.0.10
homepage: https://www.phajay.co
repository: https://github.com/lailaolabdev/flutter_phajay
issue_tracker: https://github.com/lailaolabdev/flutter_phajay/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  qr_flutter: ^4.1.0
  socket_io_client: ^3.1.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/en.png
    - assets/bcel.png
    - assets/ldb.png
    - assets/indochina.png
    - assets/jdb.png
    - assets/en.png
    - assets/logo-phajay.png
